### ISSUE TITLE
Getting error while trying to run detect_mask_video.py

### ISSUE THREAD

**Issue by Gho-S-T** [AdityaSawant21/Face-mask-detection-and-age-recognition-with-Email-Alert-System-using-ML#1]
![Screenshot 2021-06-09 154435](https://user-images.githubusercontent.com/60742189/121336958-a300f580-c939-11eb-8dc7-47d3eaf8a9f7.png)
 

How to solve this ?

**Comment by adityaasawant** [comment]
Have you pip installed all the required Modules and Libraries i.e. Keras, Tensorflow, numpy, tkinter, etc

**Comment by Gho-S-T** [comment]
Yes all libraries installed. Solved the issue raised. I'll close the
issuse.
But I'm getting error while sending email.
Can you please look into it.

smtplib.SMTPAuthenticationError: (534, b'5.7.14 <
https://accounts.google.com/signin/continue?sarp=1&scc=1&plt=AKgnsbs\n5.7.14
o2nS6K0qN01nvMXbSt7VHnr4smW-_xc2UQV5eT3fbNshxxQxkHxOaFV9KqigGV1QWehT8\n5.7.14
oMZrP2rv7gLJO978ugN3wstTTEINu8JARmfl5zP3WhVdIUhOUx8NqruN5FgoEF7n>\n5.7.14
Please log in via your web browser and then try again.\n5.7.14  Learn more
at\n5.7.14  https://support.google.com/mail/answer/78754 u5sm244953pfi.179
- gsmtp')

**Comment by adityaasawant** [comment]
Ok go to Manage your Google Account --> Security --> Less secure app access --> And turn it on on both the Senders and Receivers Mail.

**Comment by adityaasawant** [comment]
It will solve the Problem

**Comment by himadri4** [comment]
I was able to run the mask detection python files, however, the html page wasn't working even when the xampp server was working  properly . I tried everything but couldn't resolve that issue. Can you please give a step by step guide for the same.

**Comment by Gho-S-T** [comment]
Brother, mail me personally at

***@***.***

**Comment by himadri4** [comment]
Were you able to resolve this?
